export default {
  login: 'smajaas',
  id: 52218026,
  node_id: 'MDQ6VXNlcjUyMjE4MDI2',
  avatar_url: 'https://avatars.githubusercontent.com/u/52218026?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/smajaas',
  html_url: 'https://github.com/smajaas',
  followers_url: 'https://api.github.com/users/smajaas/followers',
  following_url: 'https://api.github.com/users/smajaas/following{/other_user}',
  gists_url: 'https://api.github.com/users/smajaas/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/smajaas/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/smajaas/subscriptions',
  organizations_url: 'https://api.github.com/users/smajaas/orgs',
  repos_url: 'https://api.github.com/users/smajaas/repos',
  events_url: 'https://api.github.com/users/smajaas/events{/privacy}',
  received_events_url: 'https://api.github.com/users/smajaas/received_events',
  type: 'User',
  site_admin: false,
  name: 'Mohammed Ajaas',
  company: 'DSRC',
  blog: 'https://digitalcommit.com/',
  location: 'Chennai',
  email: null,
  hireable: null,
  bio: "I'm a MERN stack dev and looking to solve real time problems",
  twitter_username: 'smajaas',
  public_repos: 122,
  public_gists: 0,
  followers: 1,
  following: 8,
  created_at: '2019-06-25T19:13:21Z',
  updated_at: '2023-07-03T03:50:49Z',
};
